### ISSUE TITLE
Reconnecting is not tested with docker

### ISSUE THREAD

**Issue by lakka** [meetings/gearsloth#30]
At the moment Docker (v1.0.1) will assign a new IP address to a container when a container is restarted. This makes testing the reconnect features of gearslothd very hard. There is a pause command in the docker command line tool, which would solve this problem by pausing the processes running in a container, but this feature is not implemented in the current Docker Remote API (v1.12).

tl;dr: the reconnecting features in gearslothd are not tested in a production-like environment, but they could be if/when Docker starts to support pause via remote api or some other means of preserving the container's IP.

**Comment by jarnoharno** [comment]
Bind to local ip: https://github.com/dotcloud/docker/issues/1139

**Comment by jarnoharno** [comment]
With remote API:
    {
         "PortBindings":{ "4730/tcp": [{ "HostIp": "127.0.1.10", "HostPort": "4730" }] },
    }

**Comment by lakka** [comment]
There is a pull request regarding this #32
