### ISSUE TITLE
Object payload should be JSON serialized before sending

### ISSUE THREAD

**Issue by amv** [meetings/gearsloth#58]
Currently when I submit a job that contains a data structure as the payload parameter, the payload that is being submitted for my end user job is [object Object]

If the payload is an Object or an Array, it should be JSON serialized before sending to the end user worker.

Please add a test for this.

**Comment by amv** [comment]
The fix for this, including a test case for it, is included in #62. This can be closed after it is merged.

**Comment by tstarck** [comment]
Closing since #62 has been merged. Reopen if necessary.
