### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by tstarck** [meetings/gearsloth#79]
Gearsloth crashes with the following:

```
sloth: D: controller: worker: disconnected from localhost:4730 (%) write EPIPE
sloth: events.js:72
sloth:         throw er; // Unhandled 'error' event
sloth:               ^
sloth: Error: write EPIPE
sloth:     at errnoException (net.js:904:11)
sloth:     at Object.afterWrite (net.js:720:19)
```

I believe it happens when connection is lost to gearman server (probably all of them).

**Comment by amv** [comment]
Is this still open?

Is there a way to test connections breaking with docker containers?

**Comment by tstarck** [comment]
I think this has been superseded by #86.
