### ISSUE TITLE
Clearing old lock files

### ISSUE THREAD

**Issue by tstarck** [meetings/gearsloth#80]
In _fs.js_ there is a comment:

```
// TODO remove lock files that are older than 15 seconds to defend against previous crashes
```

Should old lock files be cleared when adapter is first initialized?

**Comment by amv** [comment]
No. There can be multiple processes spun up and if a new process always clears lock files, mayhem ensues.

There should be a garbage collection mechanism for this, just as there should be one for the unused directories in the file storages.
