### ISSUE TITLE
What is getDomain?

### ISSUE THREAD

**Issue by tstarck** [meetings/gearsloth#81]
Ejector code seems to use adapter`.getDomains` function.

That is it? Should it be in database api documentation?

**Comment by amv** [comment]
Should be in the adapter documentation. There are also other interfaces for testing purposes that the adapters have and which should be documented.

getDomains() should return an array of the domains (separated storages for tasks) which the ejector can reach. Ejector posts a separate eject function for each domain it reaches, and controllers are supposed to use a domain-specific ejector function (included in the task description by the runner) to eject tasks.

The ducumentation will get updated when the "fs-adapter" branch is merged to master.
